spring:
  profiles:
    active: prd

---
spring:
  config:
    activate:
      on-profile: dev
    config:
      import: "application-dev.yml"

---
spring:
  config:
    activate:
      on-profile: prd
    config:
      import: "application-prd.yml"
